doctor/urls.py
from django.contrib import admin
from django.urls import path, include
app_name = 'patient'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patient.urls', namespace='patient')),
    path('summernote/', include('django_summernote.urls')),

]

patient/urls.py
from django.urls import path, include
from .views import result, add_patient, home, edit_patient
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

app_name = 'patient'
urlpatterns = [
    path('', home, name='home'),
    path('add_patient', add_patient, name='add_patient'),
    path('patient/result', result, name='result'),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('image/favicon.ico'))),
    path('<int:id>/edit', edit_patient, name='edit'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

patient/models.py
from unicodedata import name
from django.db import models


# Create your models here.
GENDER = (
    ('Male', 'Male'),
    ('Female','Female')
)
class Add_patient(models.Model):
    idnational      = models.IntegerField(primary_key=True)
    file_number     = models.CharField(max_length=30, verbose_name='File Number',null=True, blank=False)
    name            = models.CharField(max_length=120, verbose_name='Name', null=True, blank=True)
    birthdate       = models.DateField(verbose_name='Birth Date')
    date            = models.DateField(verbose_name='Today Date')
    age             = models.CharField(max_length=20, verbose_name='Age' ,null=True, blank=True)
    gender          = models.CharField(max_length=10, choices=(GENDER), default=('Male'))
    adderss         = models.CharField(max_length=250, verbose_name='Address' , null=True, blank=True)
    mobile_no       = models.CharField(max_length=30, verbose_name='Phone Number', null=True, blank=True)
    diagnosis       = models.TextField(max_length=1200, verbose_name='Diagnosis', null=True, blank=True)
    wt              = models.CharField(max_length=20, verbose_name='Wt' ,null=True, blank=True)
    temp            = models.CharField(max_length=20, verbose_name='Temp', null=True, blank=True)
    treatment       = models.TextField(max_length=1200, verbose_name='Treatment', null=True, blank=True)
    next_visit_date = models.DateField(verbose_name='Next Visit Date', null=True, blank=True)
    note            = models.TextField(max_length=1200, verbose_name='Dr. Notes', null=True, blank=True)

    def __str__(self):
        return self.name or ''
        
    class Meta:
        verbose_name = "registration"
        verbose_name_plural = "registration"


class Doctor(models.Model):
    name            = models.CharField(max_length=50, verbose_name='Doctor`s name', null=True, blank=True)
    specialty       = models.CharField(max_length=50, verbose_name='Specialty', null=True, blank=True)
    mobile_number   = models.CharField(max_length=11, verbose_name='Mobile Number', null=True, blank=True)
    address         = models.CharField(max_length=500, verbose_name='Address', null=True, blank=True)
    

    def __str__(self):
        return self.name or ''
        
    class Meta:
        verbose_name = "Doctor"
        verbose_name_plural = "Doctor"


class Patient(models.Model):
    date            = models.DateField(verbose_name='Today Date')
    age             = models.CharField(max_length=20, verbose_name='Age' ,null=True, blank=True)
    diagnosis       = models.TextField(max_length=1200, verbose_name='Diagnosis', null=True, blank=True)
    wt              = models.CharField(max_length=20, verbose_name='Wt' ,null=True, blank=True)
    temp            = models.CharField(max_length=20, verbose_name='Temp', null=True, blank=True)
    treatment       = models.TextField(max_length=1200, verbose_name='Treatment', null=True, blank=True)
    note            = models.TextField(max_length=1200, verbose_name='Dr. Notes', null=True, blank=True)

    
    def __str__(self):
        return self.name or ''
             
    class Meta:
        verbose_name = "patient"
        verbose_name_plural = "patient"

class Cashf(models.Model):
    doctor          = models.ForeignKey(Doctor, verbose_name='Doctor Cashf', on_delete=models.CASCADE)
    # patient         = models.ForeignKey(Patient, verbose_name='Patient Cashf', on_delete=models.CASCADE)
    detection_cost  = models.DecimalField(max_digits=6,decimal_places=2, verbose_name='Detection Cost')
    date            = models.DateField(verbose_name='date Cashf')
    next_visit_date = models.DateField(verbose_name='Next Visit Date')

    # def __str__(self):
    #      return self.doctor or ''
             
    class Meta:
        verbose_name = "Cashf"
        verbose_name_plural = "Cashf"

class Rosheta(models.Model):
    doctor          = models.ForeignKey(Doctor, verbose_name='Doctor`s Rosheta', on_delete=models.CASCADE)
    # patient         = models.ForeignKey(Patient, verbose_name='Patient Rosheta', on_delete=models.CASCADE)
    diagnosis       = models.CharField(max_length=1200, verbose_name='Diagnosis', null=True, blank=True)
    treatment       = models.CharField(max_length=1200, verbose_name='Treatment', null=True, blank=True)
    note            = models.CharField(max_length=1200, verbose_name='Dr. Notes', null=True, blank=True)

    def __str__(self):
        return self.diagnosis or ''
             
    class Meta:
        verbose_name = "Roshita"
        verbose_name_plural = "Roshita"

patient/forms.py
from dataclasses import fields
from datetime import date
from django import forms
from .models import Add_patient, Patient
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget # to Import edit text box and tool

class CalDate(forms.DateInput):
    input_type = 'date'

class Add_patientForm(forms.ModelForm):
    date            = forms.DateField(widget=CalDate)
    birthdate       = forms.DateField(widget=CalDate)
    next_visit_date = forms.DateField(widget=CalDate)

    diagnosis       = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}))    # to edit text box and tool
    treatment       = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}))    # to edit text box and tool
    note            = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}), label='Dr. Notes')    # to edit text box and tool

    class Meta:
        model       = Add_patient
        fields      = '__all__'
        
class Update_PatientForm(forms.ModelForm):

    date            = forms.DateField(widget=CalDate, label='Today Date')
    age             = forms.CharField(max_length=20, label='Age')
    diagnosis       = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}), label='Diagnosis')
    wt              = forms.CharField(max_length=20, label='Wt')
    temp            = forms.CharField(max_length=20, label='Temp')
    treatment       = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}), label='Treatment')
    next_visit_date = forms.DateField(widget=CalDate, label='Next Visit Date')
    note            = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}), label='Dr.Notes')
    class Meta:
        model = Patient
        fields = ('date','age','diagnosis','wt','temp','treatment','next_visit_date','note')
        verbose_name = 'update_patient'
        verbose_name_plural = 'update_patients'

patient/views.py
from django.shortcuts import render, get_object_or_404, redirect
from patient.models import Add_patient
from .forms import Add_patientForm, Update_PatientForm
from django.contrib import messages
from django.db.models import Q
# Create your views here.

def home(request):
    return render(request, 'index.html')

# ---------------------------------
# Add Patient to DB From HTML File and this old methods
# ---------------------------------
# def add_patient(request):
          
#     file_number         = request.POST.get('file_number')
#     name                = request.POST.get('name')
#     birthdate           = request.POST.get('birthdate')
#     gender              = request.POST.get('gender')
#     adderss             = request.POST.get('adderss')
#     mobile_no           = request.POST.get('mobile_no')
#     diagnosis           = request.POST.get('diagnosis')
#     age                 = request.POST.get('age')
#     next_visit_date     = request.POST.get('next_visit_date')
#     treatment           = request.POST.get('treatment')
#     temp                = request.POST.get('temp')
#     wt                  = request.POST.get('wt')
#     note                = request.POST.get('note')
    
#     dataform = Add_patient(
#         file_number=file_number,
#         name=name,
#         birthdate=birthdate,
#         gender=gender,
#         adderss=adderss,
#         mobile_no=mobile_no,
#         diagnosis=diagnosis,
#         age=age,
#         next_visit_date=next_visit_date,
#         treatment=treatment,
#         wt=wt,
#         note=note,
#         temp=temp)
    
#     if request.method == 'POST':
#         dataform.save()
#     return render(request,'add-patient.html')

# ---------------------------------
# Add Patient to DB From HTML File and this file come from forms
# ---------------------------------

def add_patient(request): #def add_patient in urls
    if request.method == 'POST': #POST in form add_patient in add_patient html
        formtohtml = Add_patientForm(request.POST) # add_patientForm come from forms.py
        if formtohtml.is_valid():
            formtohtml.save() # to save data in forms
            messages.success(request, 'Add Patient Successful.')
    return render(request,'add_patient.html',{'formtohtml':Add_patientForm}) # Add_patientForm From forms.py 
# ---------------------------------
#  END Add Patient to DB Code
# ---------------------------------
# ---------------------------------
# Search From HTML File To Get Results in another files
# ---------------------------------
def result(request):
   
    queryfromhtml=request.GET['q'] # queryfromhtml to def request q and q come from html search field
    if queryfromhtml:
        # query=Add_patient.objects.filter(name__iexact=queryfromhtml)
        multple_q = Q(Q(name__iexact=queryfromhtml) | Q(file_number__iexact=queryfromhtml)) # def multple_q and Q to allow search 2 fields
        query = Add_patient.objects.filter(multple_q) # to do my search multple
        context={
            'regdr1':query # regdr to use in HTML files query my varibal in above 
        }
    else:
        context={}
    return render(request,'patient/result.html',context)
# ---------------------------------
#  END Search Results Code
# ---------------------------------


# ---------------------------------
# Search From HTML File To Get Results in another files
# ---------------------------------
# def edit_patient(request):
#     patient = get_object_or_404(Add_patient)
#     queryfromhtml=request.GET['q'] # queryfromhtml to def request q and q come from html search field
#     if queryfromhtml:
#         # query=Add_patient.objects.filter(name__iexact=queryfromhtml)
#         # multple_q = Q(Q(name__iexact=queryfromhtml) | Q(file_number__iexact=queryfromhtml)) # def multple_q and Q to allow search 2 fields
#         query = Add_patient.objects.filter(instance=patient) # to do my search multple
#         context={
#             'regdr':query # regdr to use in HTML files query my varibal in above 
#         }
#     else:
#         context={}
#     return render(request,'edit_patient.html',context)
# ---------------------------------
#  END Search Results Code
# ---------------------------------


# ---------------------------------
# Add Patient to DB From HTML File and this file come from forms
# ---------------------------------

def edit_patient(request, id): #def edit_patient in urls
    edit = get_object_or_404(Add_patient, idnational=id)
    if request.method == 'POST': #POST in form edit_patient in edit_patient html
        formtohtml = Update_PatientForm(request.POST, instance=edit) # edit_patient come from forms.py
        if formtohtml.is_valid():
            formtohtml.save() # to save data in forms
            messages.success(request, 'Update Patient Successful.')
            
    else:
        formtohtml= Update_PatientForm(instance=edit)
    return render(request,'patient/edit.html',{'updatehtml':formtohtml}) # edit_patient From forms.py 
# ---------------------------------
#  END Add Patient to DB Code
# ---------------------------------

templates/patient/edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="alert alert-info">
	<div class="container">
		<div class ='col-6 m-auto bg-white rounded'>
			<h2 class="text-center text-info">Update Patient</h2>	
			{% for msg in messages %}
			<p class="text-success">{{msg}}</p>
			{% endfor %}			
				<form method="POST">
					{% csrf_token %}
					<div class="form-group">
						{{ updatehtml | crispy }}	
					</div>
					<button class="btn btn-success" type="submit">Save Patient</button>
				</form>	
			<br>	
	</div>

	<br>
	<script type="text/javascript">
		
			 //Near checkboxes
	$('.form-check').click(function() {
		$(this).siblings('input:checkbox').prop('checked', false);
	});
	</script>
	</div>

{% endblock content %}

{% comment %} {% extends 'base.html' %}
{% load static %}
{% block content %}
<html>
<body>
<div class="bg-mage"style="background-image: url({% static '/image/bg_3.jpg' %}); background-attachment:fixed;">
      <div class="overlay"></div>
	<div class="container">
		<h2 class="text-center">Result Search</h2>
		<div class="row">
		
			<div class="col-12">
				<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
					<div class="wrapper wrapper--w680">
						<div class="card card-4">
							<div class="card-body">
								{% if formtohtml %} {% for formtohtml in formtohtml %}
								<h2 class="title">Result Search {{formtohtml.name}}</h2>
								
								<div class="row">
									
									<div class="col-md-6">
										<div class="container">
											
										<table class="table-striped"> 
											<table class="table table-hover">
												<thead>
													<tbody>
													<tr>
														<th scope="col">ID</th>
														<th scope="row">{{formtohtml.idnational}}</th>
													</tr>
													<tr>
														<th scope="col">File Number</th>
														<td>{{formtohtml.file_number}}</td>
													</tr>
													<tr>
														<th scope="col">Full Name</th>
														<td>{{formtohtml.name}}</td>
													</tr>
													<tr>
														<th scope="col">Birth Date</th>
														<td>{{formtohtml.birthdate}}</td>
													</tr>
													<tr>
														<th scope="col">Mobile No</th>
														<td>{{formtohtml.mobile_no}}</td>
													</tr>
													<tr>
														<th scope="col">Date</th>
														<td>{{formtohtml.date}}</td>
													</tr>                                
													<tr>
														<th scope="col">Diagnosis</th>
														<td>{{formtohtml.diagnosis}}</td>
													</tr>                                
													<tr>
														<th scope="col">wt</th>
														<td>{{formtohtml.wt}}</td>
													</tr>                                
													<tr>
														<th scope="col">Temp</th>
														<td>{{formtohtml.temp}}</td>
													</tr>                                
													<tr>
														<th scope="col">Treatment</th>
														<td>{{formtohtml.treatment}}</td>
													</tr>                                
													<tr>
														<th scope="col">Next Visit</th>
														<td>{{formtohtml.next_visit_date}}</td>
													</tr>
													<tr>
														<th scope="col">Notes</th>
														<td>{{formtohtml.note}}</td>
													</tr>
													 <tr>
														<th scope="col">Action</th>
														<td><button class="btn btn-success" type="submit">Save Patient</button></td>
													</tr> 
												</tbody>
											</table>
										
										{% endfor %} {% endif %}
										<p> <a href="/add_patient" class='btn btn-info'>Add Patient</a> or .. <a href="/" class='btn btn-info'>Search Patient</a></p>
										</div>
									</div>
									<div class="col-md-6">
										<img src="{% static '/image/drbaby.png' %}" alt="" class="img-fluid gambar-diri">
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

	</body>
</html>



{% endblock content %} {% endcomment %}

templates/patient/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html>
<body>
<div class="bg-mage"style="background-image: url({% static '/image/bg_3.jpg' %}); background-attachment:fixed;">
      <div class="overlay"></div>
	<div class="container">
		<h2 class="text-center">Result Search</h2>
		<div class="row">
		
			<div class="col-12">
				<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
					<div class="wrapper wrapper--w680">
						<div class="card card-4">
							<div class="card-body">
								{% if regdr1 %} {% for regdr in regdr1 %}
								<h2 class="title">Result Search {{regdr.name}}</h2>
								
								<div class="row">
									
									<div class="col-md-6">
										<div class="container">
											
										<table class="table-striped"> 
											<table class="table table-hover">
												<thead>
													<tbody>
													<tr>
														<th scope="col">ID</th>
														<th scope="row">{{regdr.idnational}}</th>
													</tr>
													<tr>
														<th scope="col">File Number</th>
														<td>{{regdr.file_number}}</td>
													</tr>
													<tr>
														<th scope="col">Full Name</th>
														<td>{{regdr.name}}</td>
													</tr>
													<tr>
														<th scope="col">Birth Date</th>
														<td>{{regdr.birthdate}}</td>
													</tr>
													<tr>
														<th scope="col">Age</th>
														<td>{{regdr.age}}</td>
													</tr>
													<tr>
														<th scope="col">Mobile No</th>
														<td>{{regdr.mobile_no}}</td>
													</tr>
													<tr>
														<th scope="col">Date</th>
														<td>{{regdr.date}}</td>
													</tr>                                
													<tr>
														<th scope="col">Diagnosis</th>
														<td>{{regdr.diagnosis |safe}}</td>
													</tr>                                
													<tr>
														<th scope="col">wt</th>
														<td>{{regdr.wt}}</td>
													</tr>                                
													<tr>
														<th scope="col">Temp</th>
														<td>{{regdr.temp}}</td>
													</tr>                                
													<tr>
														<th scope="col">Treatment</th>
														<td>{{regdr.treatment |safe}}</td>
													</tr>                                
													<tr>
														<th scope="col">Next Visit</th>
														<td>{{regdr.next_visit_date}}</td>
													</tr>
													<tr>
														<th scope="col">Notes</th>
														<td>{{regdr.note|safe}}</td>
													</tr>
													<tr>
														<th scope="col">Action</th>
														<td><a href="{% url 'patient:edit' regdr.idnational  %}" class="btn btn-info btm-sm">Modify Patient</a></td>
													</tr>
												</tbody>
											</table>
										
											{% endfor %} {% else %}
											<h2 style="color: darkred;">
												Please Put Correct ID Number
											</h2>
											{% endif %}
										<p> <a href="add_patient" class='btn btn-info'>Add Patient</a> or .. <a href="/" class='btn btn-info'>Search Patient</a></p>
										</div>
									</div>
									<div class="col-md-6">
										<img src="{% static '/image/drbaby.png' %}" alt="" class="img-fluid gambar-diri">
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

	</body>
</html>



{% endblock content %}